#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
Convert human-readable labels into numeric labels
'''

from __future__ import print_function

import os
import argparse

parser = argparse.ArgumentParser()

parser.add_argument('LABELS_FILE')
parser.add_argument('INPUT_DIR')
parser.add_argument('OUTPUT_DIR')

args = parser.parse_args()

labels_file = args.LABELS_FILE
input_dir = args.INPUT_DIR
output_dir = args.OUTPUT_DIR

name_to_label = {}
with open(labels_file, 'r') as f:
    for label, line in enumerate(f, start=1):
        names = line.strip().split()

        for name in names:
            if name in name_to_label:
                raise ValueError('Same name for different label: {}'.format(name))

            name_to_label[name] = label

annotations = os.listdir(input_dir)

if not os.path.exists(output_dir):
    os.makedirs(output_dir)

for i, annotation in enumerate(annotations, start=1):
    names, coords = [], []

    print('{}/{}'.format(i, len(annotations)))
    with open(os.path.join(input_dir, annotation), 'r') as f:
        for line in f:
            name, coord = line.strip().split(None, 1)
            names.append(name)
            coords.append(coord)

    labels = [name_to_label[name] for name in names]

    with open(os.path.join(output_dir, annotation), 'w') as f:
        for label, coord in zip(labels, coords):
            print('{} {}'.format(label, coord), file=f)
